In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])

In [3]:
print(arr)

[1 2 3 4]


In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [6]:
np.empty((4,4))

array([[4.64250862e-310, 1.03977794e-312, 1.01855798e-312,
        9.54898106e-313],
       [1.14587773e-312, 1.01855798e-312, 1.23075756e-312,
        1.01855798e-312],
       [1.01855798e-312, 9.76118064e-313, 1.08221785e-312,
        1.10343781e-312],
       [1.03977794e-312, 4.44659081e-322, 0.00000000e+000,
        0.00000000e+000]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
arr.shape

(2, 3)

In [12]:
arr.ndim

2

In [13]:
arr.dtype

dtype('int64')

In [14]:
arr_int = np.array([1,2,3,4])

In [17]:
arr_float = arr_int.astype(np.float64)

In [18]:
arr_float.dtype

dtype('float64')

In [19]:
arr_float

array([1., 2., 3., 4.])

In [20]:
arr_str = np.array(['1', '2', '3', '4'])

In [21]:
arr_str.dtype

dtype('<U1')

In [22]:
arr_int = arr_str.astype(np.int64)

In [23]:
arr_int.dtype

dtype('int64')

In [24]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [25]:
np.add(arr1, arr2)

array([[ 6,  8],
       [10, 12]])

In [26]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [27]:
np.multiply(arr1, arr2)

array([[ 5, 12],
       [21, 32]])

In [28]:
# subtract, divide

In [29]:
# dot 함수를 이용 행렬의 곱 계산하기

In [30]:
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

In [31]:
# 슬라이싱

In [41]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [42]:
arr_i = arr[:2,1:3]

In [43]:
arr_i

array([[2, 3],
       [5, 6]])

In [35]:
arr[0,2]

3

In [36]:
arr = np.array(([1,2,3], [4,5,6]))

In [38]:
idx = arr > 3

In [39]:
idx

array([[False, False, False],
       [ True,  True,  True]])

In [40]:
arr[idx]

array([4, 5, 6])

In [49]:
redwine = np.loadtxt(
    fname='winequality-red.csv',
    delimiter=';',
    skiprows=1
)

In [50]:
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [51]:
redwine.sum()

152084.78194

In [52]:
redwine.mean()

7.926036165311652

In [53]:
redwine.mean(axis = 0)

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])